MuPDF.NET Documentation
ArtifexSoftware/MuPDF.NET pull request #80
Opened 2024-05-27 17:58 UTC by JorjMcKie

Initial draft.

2024-05-27 21:42 UTC, jamie-lemon requested changes
I made a search for the keyword "Python"
[python-instances.txt](https://github.com/ArtifexSoftware/MuPDF.NET/files/15461929/python-instances.txt)
Can we re-write those bits?


Where we do code samples instead of `::` , can we use:
`.. code-block:: c` ( I have changed this already in a few places )

2024-05-28 12:13 UTC, JorjMcKie commented
Made the changes ... I can only hope I caught them all!

2024-05-28 12:14 UTC, JorjMcKie commented
Whenever I saw it, I have removed "history" blocks - because MuPDF.NET has no past, and it makes no sense to re-report the history of PyMuPDF.

2024-05-28 21:09 UTC, jamie-lemon approved these changes

2024-05-28 21:10 UTC, merged